const characters = [
    {
        id: 1,
        characterName: "Jon Snow",
        realName: "Kit Harington",
        house: "House Stark",
        title: "King in the North",
        dialogue: "My watch has ended.",
        quote: "The true enemy won't wait out the storm.",
        status: "Alive",
        image: "./images/jon-snow.jpg",
        description: "The bastard son of Ned Stark who rose to become Lord Commander."
    },
    {
        id: 2,
        characterName: "Daenerys Targaryen",
        realName: "Emilia Clarke",
        house: "House Targaryen",
        title: "Mother of Dragons",
        dialogue: "Dracarys.",
        quote: "I will take what is mine with fire and blood.",
        status: "Deceased",
        image: "./images/daenerys.jpg",
        description: "The exiled princess seeking to reclaim the Iron Throne."
    },
    {
        id: 3,
        characterName: "Tyrion Lannister",
        realName: "Peter Dinklage",
        house: "House Lannister",
        title: "Hand of the Queen",
        dialogue: "I drink and I know things.",
        quote: "A mind needs books as a sword needs a whetstone.",
        status: "Alive",
        image: "./images/tyrion.jpg",
        description: "A sharp-witted intellect often underestimated by his family."
    },
    {
        id: 4,
        characterName: "Arya Stark",
        realName: "Maisie Williams",
        house: "House Stark",
        title: "No One",
        dialogue: "Not today.",
        quote: "Leave one wolf alive and the sheep are never safe.",
        status: "Alive",
        image: "./images/arya.jpg",
        description: "A trained assassin seeking vengeance for her family."
    },
    {
        id: 5,
        characterName: "Cersei Lannister",
        realName: "Lena Headey",
        house: "House Lannister",
        title: "Queen Regnant",
        dialogue: "You win or you die.",
        quote: "Power is power.",
        status: "Deceased",
        image: "./images/cersei.jpg",
        description: "The ambitious and protective Queen of the Seven Kingdoms."
    },
    {
        id: 6,
        characterName: "Jaime Lannister",
        realName: "Nikolaj Coster-Waldau",
        house: "House Lannister",
        title: "The Kingslayer",
        dialogue: "The things I do for love.",
        quote: "There are no men like me. There's only me.",
        status: "Deceased",
        image: "./images/jaime.jpg",
        description: "A knight known for his complex sense of honor and skill."
    },
    {
        id: 7,
        characterName: "Sansa Stark",
        realName: "Sophie Turner",
        house: "House Stark",
        title: "Queen in the North",
        dialogue: "The lone wolf dies, but the pack survives.",
        quote: "I learn. I'm a slow learner, but I learn.",
        status: "Alive",
        image: "./images/sansa.jpg",
        description: "The survivor who rose to rule the North."
    },
    {
        id: 8,
        characterName: "The Night King",
        realName: "Vladimir Furdik",
        house: "White Walkers",
        title: "Leader of the Dead",
        dialogue: "[Silent]",
        quote: "The storm is coming.",
        status: "Destroyed",
        image: "./images/night-king.jpg",
        description: "The ancient leader of the Army of the Dead."
    },
    {
        id: 9,
        characterName: "Ned Stark",
        realName: "Sean Bean",
        house: "House Stark",
        title: "Warden of the North",
        dialogue: "Winter is coming.",
        quote: "The man who passes the sentence should swing the sword.",
        status: "Deceased",
        image: "./images/ned-stark.jpg",
        description: "The honorable Lord of Winterfell whose death sparked the war."
    },
    {
        id: 10,
        characterName: "Khal Drogo",
        realName: "Jason Momoa",
        house: "Dothraki",
        title: "Great Khal",
        dialogue: "Moon of my life.",
        quote: "A Khal who cannot ride is no Khal.",
        status: "Deceased",
        image: "./images/khal-drogo.jpg",
        description: "The powerful leader of the Dothraki Great Grass Sea."
    },
    {
        id: 11,
        characterName: "Petyr Baelish",
        realName: "Aidan Gillen",
        house: "House Baelish",
        title: "Littlefinger",
        dialogue: "Chaos is a ladder.",
        quote: "Knowledge is power.",
        status: "Deceased",
        image: "./images/petyr-baelish.jpg",
        description: "The master manipulator of the royal court."
    },
    {
        id: 12,
        characterName: "Lord Varys",
        realName: "Conleth Hill",
        house: "None",
        title: "The Spider",
        dialogue: "I serve the realm.",
        quote: "The storms come and go, the big fish eat the little fish.",
        status: "Deceased",
        image: "./images/varys.jpg",
        description: "The Master of Whisperers with a network of little birds."
    },
    {
        id: 13,
        characterName: "Brienne of Tarth",
        realName: "Gwendoline Christie",
        house: "House Tarth",
        title: "Ser Brienne",
        dialogue: "I am no lady.",
        quote: "All my life men like you have sneered at me.",
        status: "Alive",
        image: "./images/brienne.jpg",
        description: "A high-born lady who chose the path of a knight."
    },
    {
        id: 14,
        characterName: "The Hound",
        realName: "Rory McCann",
        house: "House Clegane",
        title: "Sandor Clegane",
        dialogue: "You’re a talker.",
        quote: "A man's got to have a code.",
        status: "Deceased",
        image: "./images/the-hound.jpg",
        description: "A fierce warrior with a burnt face and a cynical view of knights."
    },
    {
        id: 15,
        characterName: "Joffrey Baratheon",
        realName: "Jack Gleeson",
        house: "House Baratheon",
        title: "The Cruel King",
        dialogue: "I am the King!",
        quote: "Everyone is mine to torment.",
        status: "Deceased",
        image: "./images/joffrey.jpg",
        description: "The sadistic and entitled young King on the Iron Throne."
    },
    {
        id: 16,
        characterName: "Theon Greyjoy",
        realName: "Alfie Allen",
        house: "House Greyjoy",
        title: "Prince of Winterfell",
        dialogue: "What is dead may never die.",
        quote: "I always wanted to do the right thing.",
        status: "Deceased",
        image: "./images/theon.jpg",
        description: "A man torn between his loyalty to the Starks and his own family."
    },
    {
        id: 17,
        characterName: "Melisandre",
        realName: "Carice van Houten",
        house: "None",
        title: "The Red Woman",
        dialogue: "The night is dark and full of terrors.",
        quote: "Death by fire is the purest death.",
        status: "Deceased",
        image: "./images/melisandre.jpg",
        description: "A priestess of the Lord of Light with mysterious powers."
    },
    {
        id: 18,
        characterName: "Samwell Tarly",
        realName: "John Bradley",
        house: "House Tarly",
        title: "The Grand Maester",
        dialogue: "I'm a coward.",
        quote: "I read it in a book.",
        status: "Alive",
        image: "./images/samwell.jpg",
        description: "A loyal friend to Jon Snow and a man of immense knowledge."
    },
    {
        id: 19,
        characterName: "Bronn",
        realName: "Jerome Flynn",
        house: "House Stokeworth",
        title: "Lord of Highgarden",
        dialogue: "Give me ten good men.",
        quote: "There's no honor in a dead man.",
        status: "Alive",
        image: "./images/bronn.jpg",
        description: "A skilled sellsword who fights for the highest bidder."
    },
    {
        id: 20,
        characterName: "Margaery Tyrell",
        realName: "Natalie Dormer",
        house: "House Tyrell",
        title: "Queen Consort",
        dialogue: "I want to be the Queen.",
        quote: "I'm not a queen, I'm a person.",
        status: "Deceased",
        image: "./images/margaery.jpg",
        description: "A clever and politically savvy Queen beloved by the people."
    }
];

export default characters;